sourcefuse/angular-boilerplate

README.md

Refactored boilerplate readme for better understanding
Fixes # (issue)

Refactored boilerplate readme

---

projects/saas-ui/src/app/main/components/add-plan/add-plan.component.html
projects/saas-ui/src/app/main/components/add-plan/add-plan.component.scss
projects/saas-ui/src/app/main/components/add-plan/add-plan.component.ts
projects/saas-ui/src/app/main/components/billing-plan/billing-plan.component.html
projects/saas-ui/src/app/main/components/billing-plan/billing-plan.component.scss
projects/saas-ui/src/app/main/components/button-renderer/button-renderer.component.html
projects/saas-ui/src/app/main/components/button-renderer/button-renderer.component.scss
projects/saas-ui/src/app/main/components/lead-list/lead-list.component.html
projects/saas-ui/src/app/main/components/lead-list/lead-list.component.scss
projects/saas-ui/src/app/main/components/lead-list/lead-list.component.ts
projects/saas-ui/src/app/main/components/manage-plans/manage-plans.component.html
projects/saas-ui/src/app/main/components/manage-plans/manage-plans.component.scss
projects/saas-ui/src/app/main/components/manage-plans/manage-plans.component.ts
projects/saas-ui/src/app/main/components/onboarding-tenant-list/onboarding-tenant-list.component.html
projects/saas-ui/src/app/main/components/onboarding-tenant-list/onboarding-tenant-list.component.scss
projects/saas-ui/src/app/main/components/onboarding-tenant-list/onboarding-tenant-list.component.ts
projects/saas-ui/src/app/main/main.component.html
projects/saas-ui/src/app/main/main.component.scss
projects/saas-ui/src/app/main/styles/grid-styles.scss
projects/saas-ui/src/app/on-boarding/components/add-lead/add-lead.component.html
projects/saas-ui/src/app/on-boarding/components/add-tenant/add-tenant.component.html
projects/saas-ui/src/app/on-boarding/components/add-tenant/add-tenant.component.scss

change in design
GH-34
Change in all the listing component designs
Fixes #34 

style(arc-saas): change in design

---

angular.json
projects/saas-ui/src/app/on-boarding/components/add-lead/add-lead.component.scss
projects/saas-ui/src/app/on-boarding/components/add-tenant/add-tenant.component.scss
projects/saas-ui/src/app/on-boarding/components/email-verification/email-verification.component.scss
projects/saas-ui/src/app/on-boarding/components/verification-complete/verification-complete.component.scss
projects/saas-ui/src/app/on-boarding/styles/forms.style.scss

responsiveness of on-boarding module
GH-34
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #34 

style(arc-saas): Responsive pages of  on-boarding module

---

projects/saas-ui/src/app/main/components/add-plan/add-plan.component.html
projects/saas-ui/src/app/main/components/add-plan/add-plan.component.scss
projects/saas-ui/src/app/main/styles/grid-styles.scss

responsive screens of main module
GH-34
responsive screens of main module
Fixes #34 

style(arc-saas): responsive screens of main module

---

projects/saas-ui/src/app/shared/auth/auth.component.html
projects/saas-ui/src/app/shared/auth/auth.component.scss
projects/saas-ui/src/app/shared/auth/login/login.component.scss

responsive screen of login page
Fixes #34 

style(arc-saas): responsive screen of login page

---

projects/saas-ui/src/app/main/components/onboarding-tenant-list/onboarding-tenant-list.component.scss
projects/saas-ui/src/app/main/components/onboarding-tenant-list/onboarding-tenant-list.component.ts
projects/saas-ui/src/app/main/main.component.scss

tested changes of hyperlink with changes
GH-34
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #34

fix(arc-saas): tested changes of Tenant hyperlink 

---

projects/saas-ui/src/app/main/commands/get-total-billing-plan.command.ts
projects/saas-ui/src/app/main/commands/get-total-lead.command.ts
projects/saas-ui/src/app/main/commands/get-total-plan.command.ts
projects/saas-ui/src/app/main/commands/get-total-tenant.command.ts
projects/saas-ui/src/app/main/commands/index.ts
projects/saas-ui/src/app/main/components/button-renderer/button-renderer.component.ts
projects/saas-ui/src/app/main/components/lead-list/lead-list.component.html
projects/saas-ui/src/app/main/components/lead-list/lead-list.component.ts
projects/saas-ui/src/app/main/components/manage-plans/manage-plans.component.html
projects/saas-ui/src/app/main/components/manage-plans/manage-plans.component.ts
projects/saas-ui/src/app/main/components/onboarding-tenant-list/onboarding-tenant-list.component.html
projects/saas-ui/src/app/main/components/onboarding-tenant-list/onboarding-tenant-list.component.ts
projects/saas-ui/src/app/main/main.component.scss
projects/saas-ui/src/app/main/styles/grid-styles.scss
projects/saas-ui/src/app/on-boarding/commands/get-plan.command.ts
projects/saas-ui/src/app/on-boarding/components/add-tenant/add-tenant.component.ts
projects/saas-ui/src/app/shared/services/billing-plan-service.ts
projects/saas-ui/src/app/shared/services/on-boarding-service.ts
projects/saas-ui/src/app/shared/services/tenant-list-facade.service.ts

pagination of components
GH-34
pagination for 3 components named 
plan component,lead list componet, Tenant list component
Fixes #34 

fix(arc-saas): pagination of components

---

projects/saas-ui/src/app/main/components/billing-plan/billing-plan.component.html
projects/saas-ui/src/app/main/components/billing-plan/billing-plan.component.ts
projects/saas-ui/src/app/shared/services/billing-plan-service.ts

Pagination of billing component
Fixes #34 

fix(saas-ui):pagination of billing component

---

projects/arc-lib/src/lib/core/auth/auth.service.ts
projects/arc-lib/src/lib/core/auth/commands/cognito-logout-command.ts
projects/saas-ui/src/app/main/components/onboarding-tenant-list/onboarding-tenant-list.component.scss
projects/saas-ui/src/app/main/main.component.scss
projects/saas-ui/src/app/main/main.component.ts
projects/saas-ui/src/environment.ts

fix cognito logout
GH-48
fix cognito logout
Fixes #48 

fix(arc-saas): fix cognito logout

---

projects/arc-docs/src/app/docs/docs-routing.module.ts
projects/arc-docs/src/app/docs/docs.component.html
projects/arc-docs/src/app/docs/guide/components/backend-integration-doc/backend-integration-doc.component.html
projects/arc-docs/src/app/docs/guide/components/backend-integration-doc/backend-integration-doc.component.spec.ts
projects/arc-docs/src/app/docs/guide/components/backend-integration-doc/backend-integration-doc.component.ts
projects/arc-docs/src/app/docs/guide/components/clone-boilerplate-doc/clone-boilerplate-doc.component.scss
projects/arc-docs/src/app/docs/guide/components/clone-boilerplate-doc/clone-boilerplate-doc.component.spec.ts
projects/arc-docs/src/app/docs/guide/components/clone-boilerplate-doc/clone-boilerplate-doc.component.ts
projects/arc-docs/src/app/docs/guide/guide-routing.module.ts
projects/arc-docs/src/app/docs/guide/guide.module.ts
projects/arc-lib/src/lib/components/cli-wrapper/cli-wrapper.component.html
projects/arc-lib/src/lib/components/cli-wrapper/cli-wrapper.component.scss
projects/arc-lib/src/lib/components/cli-wrapper/cli-wrapper.component.ts
projects/arc-lib/src/lib/components/header /header.component.html
projects/arc-lib/src/lib/components/header /header.component.scss
projects/arc-lib/src/lib/components/header/header.component.ts
projects/arc/src/app/main/home/home.component.scss
projects/arc/src/styles.scss

Documentation of Cloning Arc-Angular-Boilerplate
Fixes #26 ,#27

Documentation of Cloning Boilerplate

---

projects/arc-docs/src/app/docs/auth-doc/auth-doc-routing.module.ts
projects/arc-docs/src/app/docs/auth-doc/auth-doc.module.ts
projects/arc-docs/src/app/docs/auth-doc/components/doc-introdution/doc-introdution.component.html
projects/arc-docs/src/app/docs/auth-doc/components/doc-introdution/doc-introdution.component.scss
projects/arc-docs/src/app/docs/auth-doc/components/doc-introdution/doc-introdution.component.spec.ts
projects/arc-docs/src/app/docs/auth-doc/components/doc-introdution/doc-introdution.component.ts
projects/arc-docs/src/app/docs/docs-routing.module.ts

adding Auth module. documentation
Fixes #26 

feat(arc-docs):auth module. documentation

---

projects/arc-lib/src/lib/core/validators.ts
projects/saas-ui/src/app/main/commands/index.ts
projects/saas-ui/src/app/main/commands/register-tenant.command.ts
projects/saas-ui/src/app/main/components/onboarding-tenant-list/onboarding-tenant-list.component.html
projects/saas-ui/src/app/main/components/onboarding-tenant-list/onboarding-tenant-list.component.scss
projects/saas-ui/src/app/main/components/onboarding-tenant-list/onboarding-tenant-list.component.ts
projects/saas-ui/src/app/main/components/tenant-registration/tenant-registration.component.html
projects/saas-ui/src/app/main/components/tenant-registration/tenant-registration.component.scss
projects/saas-ui/src/app/main/components/tenant-registration/tenant-registration.component.spec.ts
projects/saas-ui/src/app/main/components/tenant-registration/tenant-registration.component.ts
projects/saas-ui/src/app/main/main-routing.module.ts
projects/saas-ui/src/app/main/main.module.ts
projects/saas-ui/src/app/main/styles/grid-styles.scss
projects/saas-ui/src/app/on-boarding/components/add-lead/add-lead.component.html
projects/saas-ui/src/app/on-boarding/components/add-tenant/add-tenant.component.html
projects/saas-ui/src/app/on-boarding/components/add-tenant/add-tenant.component.scss
projects/saas-ui/src/app/on-boarding/components/add-tenant/add-tenant.component.ts
projects/saas-ui/src/app/shared/models/tenantLead.model.ts
projects/saas-ui/src/app/shared/services/billing-plan-service.ts
projects/saas-ui/src/app/shared/services/on-boarding-service.ts
projects/saas-ui/src/styles.scss

To combine Lead component and Tenant component and show that component after login
Fixes #63 

feat(arc-saas): Enable tenant registration via super admin 

---

projects/saas-ui/src/app/main/components/tenant-registration/tenant-registration.component.html
projects/saas-ui/src/app/main/components/tenant-registration/tenant-registration.component.ts
projects/saas-ui/src/app/on-boarding/components/add-lead/add-lead.component.html
projects/saas-ui/src/app/on-boarding/components/add-lead/add-lead.component.scss
projects/saas-ui/src/app/on-boarding/components/add-lead/add-lead.component.ts
projects/saas-ui/src/app/shared/constants/countries.constant.ts

country as a dropdown field in Tenant Registration form
Fixes #80 

fix(arc-saas): country as a dropdown field

---

projects/saas-ui/src/app/main/components/add-plan/add-plan.component.html
projects/saas-ui/src/app/main/components/add-plan/add-plan.component.ts
projects/saas-ui/src/app/shared/models/feature.model.ts

adding new feature named identity feature
Fixes #85

feat(arc-saas): adding new feature named identity feature

---

package-lock.json
projects/saas-ui/src/app/main/styles/grid-styles.scss
projects/saas-ui/src/app/on-boarding/commands/add-subscriber-command.ts
projects/saas-ui/src/app/on-boarding/commands/get-all-tenant-command.ts
projects/saas-ui/src/app/on-boarding/commands/index.ts
projects/saas-ui/src/app/on-boarding/components/add-subscriber/add-subscriber.component.html
projects/saas-ui/src/app/on-boarding/components/add-subscriber/add-subscriber.component.scss
projects/saas-ui/src/app/on-boarding/components/add-subscriber/add-subscriber.component.spec.ts
projects/saas-ui/src/app/on-boarding/components/add-subscriber/add-subscriber.component.ts
projects/saas-ui/src/app/on-boarding/on-boarding-routing.module.ts
projects/saas-ui/src/app/on-boarding/on-boarding.module.ts
projects/saas-ui/src/app/shared/models/index.ts
projects/saas-ui/src/app/shared/models/key.model.ts
projects/saas-ui/src/app/shared/models/subscriber.model.ts
projects/saas-ui/src/app/shared/services/on-boarding-service.ts

add subscription component for marketplace

---

projects/saas-ui/src/app/main/commands/get-tenant-details.command.ts
projects/saas-ui/src/app/main/commands/index.ts
projects/saas-ui/src/app/main/components/eye-icon-renderer/eye-icon-renderer.component.html
projects/saas-ui/src/app/main/components/eye-icon-renderer/eye-icon-renderer.component.scss
projects/saas-ui/src/app/main/components/eye-icon-renderer/eye-icon-renderer.component.spec.ts
projects/saas-ui/src/app/main/components/eye-icon-renderer/eye-icon-renderer.component.ts
projects/saas-ui/src/app/main/components/onboarding-tenant-list/onboarding-tenant-list.component.html
projects/saas-ui/src/app/main/components/onboarding-tenant-list/onboarding-tenant-list.component.scss
projects/saas-ui/src/app/main/components/onboarding-tenant-list/onboarding-tenant-list.component.spec.ts
projects/saas-ui/src/app/main/components/onboarding-tenant-list/onboarding-tenant-list.component.ts
projects/saas-ui/src/app/main/components/tenant-detail/tenant-detail.component.html
projects/saas-ui/src/app/main/components/tenant-detail/tenant-detail.component.scss
projects/saas-ui/src/app/main/components/tenant-detail/tenant-detail.component.spec.ts
projects/saas-ui/src/app/main/components/tenant-detail/tenant-detail.component.ts
projects/saas-ui/src/app/main/main-routing.module.ts
projects/saas-ui/src/app/main/main.module.ts
projects/saas-ui/src/app/shared/models/tenantDetails.model.ts
projects/saas-ui/src/app/shared/services/tenant-list-facade.service.ts

1.) adding list of tenant with of the details like subscription plan , plan details etc
Fixes #76 

fix(arc-saas): detailed list of tenant onboarding

---

projects/saas-ui/src/app/main/components/onboarding-tenant-list/onboarding-tenant-list.component.ts
projects/saas-ui/src/app/shared/models/tenantDetails.model.ts

GH-93
key and status issue in onboarding list component resolved 
Fixes #93 

fix(arc-saas): key and status issue in onboarding list component 

---

projects/saas-ui/src/app/main/components/add-plan/add-plan.component.ts

Update the feature when edit the plan
Fixes #91 

(Arc-Saas):Update the feature when edit the plan

---

.cz-config.js
package-lock.json
package.json

GH-00
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)

chore(ci-cd): update the zonejs deps

---

angular.json

Resolved UI bug login image not visible on prod
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Tested Locally

fix(arc-saas):  UI login image not visible 

---

projects/saas-ui/src/app/main/components/billing-plan/billing-plan.component.html
projects/saas-ui/src/app/main/components/billing-plan/billing-plan.component.ts
projects/saas-ui/src/app/main/components/lead-list/lead-list.component.html
projects/saas-ui/src/app/main/components/lead-list/lead-list.component.ts
projects/saas-ui/src/app/main/components/manage-plans/manage-plans.component.html
projects/saas-ui/src/app/main/components/manage-plans/manage-plans.component.scss
projects/saas-ui/src/app/main/components/manage-plans/manage-plans.component.ts
projects/saas-ui/src/app/main/components/onboarding-tenant-list/onboarding-tenant-list.component.html
projects/saas-ui/src/app/main/components/onboarding-tenant-list/onboarding-tenant-list.component.scss
projects/saas-ui/src/app/main/components/onboarding-tenant-list/onboarding-tenant-list.component.ts
projects/saas-ui/src/app/main/styles/grid-styles.scss

Appling loader to resolve delay in data display issue
Fixes #106 
tested locally

fix(arc-saas): Appling loader to resolve delay in data display issue

---

projects/arc-lib/src/lib/core/auth/auth.service.ts
projects/saas-ui/src/app/shared/auth/login/login.component.html
projects/saas-ui/src/app/shared/auth/login/login.component.scss
projects/saas-ui/src/app/shared/auth/login/login.component.ts

integrated keycloak login
GH-118
integrated keycloak login
Fixes #118 

feat(arc-saas): integrate keycloak login
